# Generated by Django 5.0.6 on 2024-06-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='Факультет')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Кафедра')),
            ],
        ),
    ]
