# Generated by Django 5.0.6 on 2024-06-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0002_usermanager_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_publications', models.CharField(max_length=100, verbose_name='Тип публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('quarter', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Квартал')),
                ('department', models.CharField(max_length=100, verbose_name='Кафедра')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.usermanager', verbose_name='Ответсвенный')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_author', models.CharField(blank=True, max_length=100, verbose_name='ФИО автора')),
                ('name_publication', models.CharField(blank=True, max_length=1000, verbose_name='Наименование публикации')),
                ('exit_data', models.TextField(verbose_name='Выходные данные публикации (Название журнала, Номер, Том, страницы)')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('place_publication', models.TextField(verbose_name='Место опубликования')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
                ('type_publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typepublications', verbose_name='Тип публикации')),
            ],
        ),
    ]
