# Generated by Django 5.0.6 on 2024-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0003_typepublications_map_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='status',
            field=models.CharField(choices=[('E', 'Edited'), ('с', 'Completed')], default='Edited', max_length=20),
        ),
    ]
