# Generated by Django 5.0.6 on 2024-06-05 01:13

import gos_map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0004_map_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='status',
            field=models.CharField(choices=[('E', 'Редактируется'), ('с', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='map',
            name='year',
            field=gos_map.models.YearField(validators=[gos_map.models.validate_year, gos_map.models.validate_year]),
        ),
    ]
