# Generated by Django 5.0.6 on 2024-06-05 01:13

import gos_map.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0006_alter_map_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='year',
            field=gos_map.models.YearField(validators=[gos_map.models.validate_year, gos_map.models.validate_year]),
        ),
    ]
