# Generated by Django 5.0.6 on 2024-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0007_alter_map_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
