# Generated by Django 5.0.6 on 2024-06-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0008_alter_map_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='status',
            field=models.CharField(choices=[('E', 'Редактируется'), ('с', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус'),
        ),
    ]
