# Generated by Django 5.0.6 on 2024-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0009_publications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='doi_publication',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DOI публикации'),
        ),
        migrations.AddField(
            model_name='publications',
            name='eLIBRARY_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='eLIBRARY ID'),
        ),
        migrations.AddField(
            model_name='publications',
            name='volume_publication',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем публикации (п.л.)'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='exit_data',
            field=models.TextField(blank=True, verbose_name='Выходные данные публикации (Название журнала, Номер, Том, страницы)'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='place_publication',
            field=models.TextField(blank=True, verbose_name='Место опубликования'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Год'),
        ),
    ]
