# Generated by Django 5.0.6 on 2024-06-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0010_publications_doi_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='position',
            field=models.CharField(blank=True, choices=[('НА', 'Научный отдел'), ('ЗДН', 'Заместитель декана по научной работе'), ('ЗК', 'Rаведующий кафедрой')], max_length=100, verbose_name='Должность'),
        ),
    ]
