# Generated by Django 5.0.6 on 2024-06-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0011_alter_usermanager_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='position',
            field=models.CharField(blank=True, choices=[('НО', 'Научный отдел'), ('ЗДпоНр', 'Заместитель декана по научной работе'), ('ЗК', 'Заведующий кафедрой')], max_length=100, verbose_name='Должность'),
        ),
    ]
