# Generated by Django 5.0.6 on 2024-06-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0012_alter_usermanager_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_documents', models.CharField(max_length=100, verbose_name='Тип документа')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_Property', models.CharField(max_length=100, verbose_name='Вид интеллектуальной собственности')),
            ],
        ),
        migrations.AlterField(
            model_name='publications',
            name='full_name_author',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='position',
            field=models.CharField(blank=True, choices=[('НО', 'Научный отдел'), ('ЗДпоНР', 'Заместитель декана по научной работе'), ('ЗК', 'Заведующий кафедрой')], max_length=100, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='SecurityDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_author', models.CharField(blank=True, max_length=200, verbose_name='ФИО автора')),
                ('name_publication', models.CharField(blank=True, max_length=1000, verbose_name='Наименование публикации')),
                ('status', models.CharField(choices=[('E', 'Редактируется'), ('с', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус')),
                ('application_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер заявки / патента')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typedocuments', verbose_name='Тип документа')),
                ('type_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typeproperty', verbose_name='Вид интеллектуальной собственности')),
            ],
        ),
    ]
