# Generated by Django 5.0.6 on 2024-06-19 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0013_typedocuments_typeproperty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карты', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name': 'Публикации', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='securitydocuments',
            options={'verbose_name': 'Охранные документы', 'verbose_name_plural': 'Охранные документы'},
        ),
        migrations.AlterModelOptions(
            name='typedocuments',
            options={'verbose_name': 'Тип документа', 'verbose_name_plural': 'Тип документа'},
        ),
        migrations.AlterModelOptions(
            name='typeproperty',
            options={'verbose_name': 'Вид интеллектуальной собственности', 'verbose_name_plural': 'Вид интеллектуальной собственности'},
        ),
        migrations.AlterModelOptions(
            name='typepublications',
            options={'verbose_name': 'Тип публикации', 'verbose_name_plural': 'Тип публикации'},
        ),
        migrations.AlterField(
            model_name='publications',
            name='volume_publication',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем публикации (п.л.)'),
        ),
    ]
