# Generated by Django 5.0.6 on 2024-06-19 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0014_alter_map_options_alter_publications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='volume_publication',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем публикации (п.л.)'),
        ),
    ]
