# Generated by Django 5.0.6 on 2024-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0015_alter_publications_volume_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydocuments',
            name='full_name_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО автора'),
        ),
        migrations.AlterField(
            model_name='securitydocuments',
            name='name_publication',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Наименование публикации'),
        ),
    ]
