# Generated by Django 5.0.6 on 2024-06-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0016_alter_securitydocuments_full_name_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='full_name_author',
            new_name='full_name_author_publications',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='name_publication',
            new_name='name_publication_publications',
        ),
        migrations.RenameField(
            model_name='securitydocuments',
            old_name='full_name_author',
            new_name='full_name_author_security_documents',
        ),
        migrations.RenameField(
            model_name='securitydocuments',
            old_name='name_publication',
            new_name='name_publication_security_documents',
        ),
    ]
