# Generated by Django 5.0.6 on 2024-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0017_rename_full_name_author_publications_full_name_author_publications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMonographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_monographs', models.CharField(max_length=100, verbose_name='Вид интеллектуальной собственности')),
            ],
        ),
        migrations.RenameField(
            model_name='typeproperty',
            old_name='name_type_Property',
            new_name='name_type_property',
        ),
        migrations.AlterField(
            model_name='map',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
