# Generated by Django 5.0.6 on 2024-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0018_monographs_typemonographs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monographs',
        ),
        migrations.AlterModelOptions(
            name='typemonographs',
            options={'verbose_name': 'Тип монографии', 'verbose_name_plural': 'Тип монографии'},
        ),
        migrations.AlterField(
            model_name='securitydocuments',
            name='name_publication_security_documents',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование публикации'),
        ),
        migrations.AlterField(
            model_name='typemonographs',
            name='name_type_monographs',
            field=models.CharField(max_length=100, verbose_name='Тип монографии'),
        ),
    ]
