# Generated by Django 5.0.6 on 2024-06-20 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0019_delete_monographs_alter_typemonographs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_author_Monographs', models.TextField(blank=True, null=True, verbose_name='Автор(ы) ФИО (полностью)')),
                ('name_works', models.TextField(blank=True, null=True, verbose_name='Название работы')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
                ('type_monographs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typemonographs', verbose_name='Тип монографии')),
            ],
        ),
    ]
