# Generated by Django 5.0.6 on 2024-06-20 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0020_monographs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monographs',
            options={'verbose_name': 'Монографии', 'verbose_name_plural': 'Монографии'},
        ),
        migrations.AddField(
            model_name='monographs',
            name='circulation',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
        ),
        migrations.AddField(
            model_name='monographs',
            name='publishing_house',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Издательство (наименование)'),
        ),
        migrations.AddField(
            model_name='monographs',
            name='status',
            field=models.CharField(choices=[('E', 'Редактируется'), ('с', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='monographs',
            name='type_publishing_house',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Вид издательство'),
        ),
        migrations.AddField(
            model_name='monographs',
            name='volume_monographs',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='monographs',
            name='year_of_publication_monographs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год издание'),
        ),
    ]
