# Generated by Django 5.0.6 on 2024-06-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0021_alter_monographs_options_monographs_circulation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_events', models.CharField(max_length=100, verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Тип мероприятия',
            },
        ),
        migrations.CreateModel(
            name='TypeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_participation', models.CharField(max_length=100, verbose_name='Тип участия')),
            ],
            options={
                'verbose_name': 'Тип участия',
                'verbose_name_plural': 'Тип участия',
            },
        ),
        migrations.RenameField(
            model_name='monographs',
            old_name='full_name_author_Monographs',
            new_name='full_name_author_monographs',
        ),
    ]
