# Generated by Django 5.0.6 on 2024-06-23 01:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0022_typeevent_typeparticipation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_author_event', models.TextField(blank=True, null=True, verbose_name='ФИО (полностью) участников ЗабГУ')),
                ('name_event', models.TextField(blank=True, null=True, verbose_name='Название мероприятия')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень (международное, всероссийское и др.)')),
                ('title_report', models.TextField(blank=True, null=True, verbose_name='Наименование Доклада на мероприятия (для конференций)')),
                ('date_event', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('place_event', models.TextField(blank=True, null=True, verbose_name='Место проведения')),
                ('number_participants', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общее кол-во участников мероприятия')),
                ('number_foreign_participants', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во зарубежных участников мероприятия')),
                ('number_exhibits', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во экспонатов (для выставки)')),
                ('publication_collection', models.CharField(blank=True, max_length=100, null=True, verbose_name='С изданием сборника (для конференций)')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='Полученные награды НПР и студентами ЗабГУ (медали, дипломы, грамоты)')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на программу мероприятия')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.typeevent', verbose_name='Тип мероприятия')),
                ('type_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.typeparticipation', verbose_name='Тип участия')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
