# Generated by Django 5.0.6 on 2024-06-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0023_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('E', 'Редактируется'), ('с', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус'),
        ),
    ]
