# Generated by Django 5.0.6 on 2024-06-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0024_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
    ]
