# Generated by Django 5.0.6 on 2024-06-23 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0026_alter_event_date_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_grant', models.CharField(max_length=100, verbose_name='Тип гранта')),
            ],
            options={
                'verbose_name': 'Тип гранта',
                'verbose_name_plural': 'Тип гранта',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fund', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование фонда')),
                ('name_competition', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование конкурса')),
                ('kod_competition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код конкурса')),
                ('nomination', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номинация (при наличии)')),
                ('name_project_topic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование темы проекта (без кавычек)')),
                ('project_manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='Руководитель проекта (ФИО полностью)')),
                ('number_project_team', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Численность проектного коллектива')),
                ('number_young_scientists', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Численность молодых ученых')),
                ('full_name_performer', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО (полностью) исполнителей')),
                ('winner', models.CharField(choices=[('Д', 'Да'), ('Н', 'Нет')], default='Редактируется', max_length=3, verbose_name='Выиграно (Да, Нет)')),
                ('status', models.CharField(choices=[('E', 'Редактируется'), ('с', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
                ('type_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.typegrant', verbose_name='Тип гранта')),
            ],
            options={
                'verbose_name': 'Грант',
                'verbose_name_plural': 'Грант',
            },
        ),
    ]
