# Generated by Django 5.0.6 on 2024-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0027_typegrant_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='winner',
            field=models.CharField(choices=[('Д', 'Да'), ('Н', 'Нет')], default='Нет', max_length=3, verbose_name='Выиграно (Да, Нет)'),
        ),
    ]
