# Generated by Django 5.0.6 on 2024-06-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0028_alter_grant_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_form_participation', models.CharField(max_length=500, verbose_name='Форма участия')),
            ],
            options={
                'verbose_name': 'Форма участия',
                'verbose_name_plural': 'Форма участия',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_event',
            new_name='date_event_event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name_event',
            new_name='name_event_event',
        ),
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typeevent', verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typeparticipation', verbose_name='Тип участия'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('Р', 'Редактируется'), ('З', 'Завершено')], default='Р', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='type_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typegrant', verbose_name='Тип гранта'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='winner',
            field=models.CharField(choices=[('Д', 'Да'), ('Н', 'Нет')], default='Н', max_length=3, verbose_name='Выиграно (Да, Нет)'),
        ),
        migrations.CreateModel(
            name='NIRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_students', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО студентов')),
                ('name_event_nirs', models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование мероприятия')),
                ('full_name_scientific_supervisor', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО научного руководителя')),
                ('awards_diplomas', models.TextField(blank=True, null=True, verbose_name='Награды/Дипломы')),
                ('date_event_nirs', models.DateField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('status', models.CharField(choices=[('Р', 'Редактируется'), ('З', 'Завершено')], default='Р', max_length=20, verbose_name='Статус')),
                ('form_participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.formparticipation', verbose_name='Карта')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'НИРС',
                'verbose_name_plural': 'НИРС',
            },
        ),
    ]
