# Generated by Django 5.0.6 on 2024-06-23 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0029_formparticipation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nirs',
            name='number_students',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Численность студентов'),
        ),
        migrations.AlterField(
            model_name='nirs',
            name='full_name_students',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО студентов'),
        ),
    ]
