# Generated by Django 5.0.6 on 2024-06-23 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0030_nirs_number_students_alter_nirs_full_name_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nirs',
            name='form_participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.formparticipation', verbose_name='Карта'),
        ),
        migrations.CreateModel(
            name='PopularSciencePublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_author', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ф.И.О. автора (полностью)')),
                ('name_publication_popular_science_publications', models.CharField(blank=True, max_length=1000, verbose_name='Название публикации')),
                ('place_publication', models.TextField(blank=True, null=True, verbose_name='Место опубликования, издательство, год, № выпуска')),
                ('volume_popular_science_publications', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем публикации')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('Р', 'Редактируется'), ('З', 'Завершено')], default='Р', max_length=20, verbose_name='Статус')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Научно-популярные издания',
                'verbose_name_plural': 'Научно-популярные издания',
            },
        ),
    ]
