# Generated by Django 5.0.6 on 2024-06-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0031_alter_nirs_form_participation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularsciencepublications',
            old_name='place_publication',
            new_name='place_publication_popular_science_publications',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='place_publication',
            new_name='place_publication_publications',
        ),
    ]
