# Generated by Django 5.0.6 on 2024-06-24 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0032_rename_place_publication_popularsciencepublications_place_publication_popular_science_publications_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_scientific_direction', models.CharField(blank=True, max_length=700, verbose_name='Научное направление')),
                ('name_scientific_school', models.CharField(blank=True, max_length=700, verbose_name='Название научной школы')),
                ('leading_scientists', models.TextField(blank=True, null=True, verbose_name='Ведущие ученые в данной области (1-3 человека)')),
                ('number_defended_doctoral_dissertations', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во защищенных докторских диссертаций')),
                ('number_defended_PhD_theses', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во защищенных кандидатских диссертаций')),
                ('number_monographs', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во монографий')),
                ('number_articles_WoS_Scopus', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во статей WoS/Scopus')),
                ('number_articles_VAK', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во статей ВАК')),
                ('number_articles_RIHC', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во статей РИНЦ')),
                ('number_applications_inventions', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во заявок на изобретения')),
                ('number_security_documents_received', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во полученных охранных документов')),
                ('number_organized', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во организованных международных и (или) всероссийских научных и (или) научно-практических мероприятий')),
                ('amount_funding', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем финансирования')),
                ('status', models.CharField(choices=[('Р', 'Редактируется'), ('З', 'Завершено')], default='Р', max_length=20, verbose_name='Статус')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Научные направления',
                'verbose_name_plural': 'Научные направления',
            },
        ),
    ]
