# Generated by Django 5.0.6 on 2024-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0033_scientificdirections'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullNameАuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ф.И.О.')),
            ],
        ),
    ]
