# Generated by Django 5.0.6 on 2024-06-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0034_fullnameаuthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_scientific_research', models.TextField(blank=True, null=True, verbose_name='Наименование научно-исследовательских  и научно-технических проектов ')),
                ('name_scientific_centers', models.TextField(blank=True, null=True, verbose_name='Наименование научных центров, лабораторий, других подразделений, созданнх с участвием международных или иностранных организаций')),
                ('name_topics', models.TextField(blank=True, null=True, verbose_name='Наименование тем, проводимых совместных научных исследований')),
                ('name_research_topics', models.TextField(blank=True, null=True, verbose_name='Наименование тем научных исследований, опытно-конструкторских работ, проводимых по заказам международных и иностранных организаций')),
                ('name_scientific_programs', models.TextField(blank=True, null=True, verbose_name='Наименование научных программ, разработка и реализация которых осуществляется  совместно с международными или иностранными организациями')),
                ('status', models.CharField(choices=[('Р', 'Редактируется'), ('З', 'Завершено')], default='Р', max_length=20, verbose_name='Статус')),
                ('id_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos_map.map', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Международное сотрудничество',
                'verbose_name_plural': 'Международное сотрудничество',
            },
        ),
    ]
