# Generated by Django 5.0.6 on 2024-06-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0035_internationalcooperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='type_grant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typegrant', verbose_name='Тип гранта'),
        ),
    ]
