# Generated by Django 5.0.6 on 2024-06-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0036_alter_grant_type_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typeevent', verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos_map.typeparticipation', verbose_name='Тип участия'),
        ),
    ]
