# Generated by Django 5.0.6 on 2024-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0037_alter_event_type_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nirs',
            name='full_name_scientific_supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО научного руководителя'),
        ),
    ]
