# Generated by Django 5.0.6 on 2024-06-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0038_alter_nirs_full_name_scientific_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(blank=True, max_length=500, null=True, verbose_name='Кафедра')),
            ],
        ),
    ]
