# Generated by Django 5.0.6 on 2024-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0040_faculty_department_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publication_collection',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], default='No', max_length=100, null=True, verbose_name='С изданием сборника (для конференций)'),
        ),
        migrations.AlterField(
            model_name='map',
            name='status',
            field=models.CharField(choices=[('Редактируется', 'Редактируется'), ('Завершено', 'Завершено')], default='Редактируется', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='position',
            field=models.CharField(blank=True, choices=[('НО', 'Научный отдел'), ('ЗД', 'Заместитель декана по научной работе'), ('ЗК', 'Заведующий кафедрой')], max_length=100, verbose_name='Должность'),
        ),
    ]
