# Generated by Django 5.0.6 on 2024-06-30 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0041_alter_event_publication_collection_alter_map_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_level', models.CharField(max_length=100, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровень',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gos_map.typelevel', verbose_name='Уровень'),
        ),
    ]
