# Generated by Django 5.0.6 on 2024-06-30 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos_map', '0043_alter_event_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gos_map.typelevel', verbose_name='Уровень'),
        ),
    ]
